// Every static, user-facing string in the app lives here. Screens read them
// through useStrings() instead of hardcoding text inline — this is the one
// file to open to change copy anywhere in the product.

export const stringConstants = {
  common: {
    currency: 'XAF',
    change: 'Change',
    save: 'Save',
    continueLabel: 'Continue',
    confirm: 'Confirm',
    cancel: 'Cancel',
    back: 'Back',
    add: 'Add',
  },

  months: [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December',
  ],

  splash: {
    wordmark: 'dreda',
    headline: 'Track Your Spending and Time  Effortlessly',
    tagline:
      'Manage your time and finances easily using our intuitive user-friendly interface and set goals you can monitor.',
    getStarted: 'Get Started',
    inviteNotePrefix: 'This is an invite only platform, so if you do not have an account, get an invite at',
    inviteLink: 'www.dreda.com',
  },

  pin: {
    title: 'Enter Account PIN',
    titleCreate: 'Create Your PIN',
    continueLabel: 'Continue',
    footerNotePrefix: 'This is an invite only platform, if you have forgotten your pin, visit',
    footerNoteSuffix: 'to reset it.',
    footerLink: 'www.dreda.com',
  },

  home: {
    balanceLabel: 'Total Balance',
    spendableLabel: 'Spendable',
    unjustifiedLabel: 'Unaccounted for',
    savingsLabel: 'Savings',
    quickActionsTitle: 'Quick Actions',
    quickActionAddNew: 'Add New',
    quickActionSeeBudget: 'See Budget',
    quickActionHistory: 'History',
    quickActionDebts: 'Debts',
    wallets: 'Wallets',
    spendingBreakdown: 'Cashflow',
    periodWeek: 'Week',
    periodMonth: 'Month',
    periodQuarter: 'Quarter',
    legendIncome: 'Income',
    legendExpense: 'Expense',
    savingsTrend: 'Savings Trend',
    budgets: 'Budgets',
    upcomingPayments: 'Upcoming Payments',
    noUpcomingPayments: "You're all caught up — nothing due soon.",
    noWallets: 'Add a wallet to see it here.',
    noBudgets: 'No budgets set yet this month.',
    goalsAndDebt: 'Goals & Debt',
    goalsAndDebtMeta: 'Track savings goals and debt repayments',
    projects: 'Projects',
    projectsMeta: 'Areas, projects, and tasks',
    chooseCurrency: 'Choose currency',
    searchCurrenciesPlaceholder: 'Search currencies',
  },

  statistics: {
    acrossAllAccounts: 'Across all accounts',
    spending: 'Spending',
    totalOutflow: 'Total outflow',
    income: 'Income',
    totalInflow: 'Total inflow',
    netSavings: 'Net Savings',
    savingsRate: 'Savings Rate',
    activeAccountsSuffix: 'active accounts this month',
    spendingInsights: 'Spending Insights',
    topCategories: 'Top Categories',
    noSpendingThisMonth: 'Nothing spent yet this period.',
    thisMonthVsLastMonth: 'This Month vs Last Month',
    noComparisonYet: 'Not enough history yet to compare.',
    periods: {
      Week: 'Week',
      Month: 'Month',
      Quarter: 'Quarter',
      Year: 'Year',
    } as const,
    habitBreakdown: 'Habit Breakdown',
    habitPeriods: {
      Daily: 'Daily',
      Monthly: 'Monthly',
      Yearly: 'Yearly',
    } as const,
    habitIncome: 'Income',
    habitExpense: 'Expense',
    habitSavings: 'Savings',
    noHabitData: 'Nothing recorded in this window yet.',
    incomeAnalysis: 'Income Analysis',
    totalIncome: 'Total income',
    noIncomeThisPeriod: 'No income recorded yet this period.',
    incomeConsistency: 'Income Consistency',
    noIncomeConsistencyData: 'Need at least one month of income to compare.',
    financialTrends: 'Financial Trends',
    trendsSpending: 'Spending',
    trendsIncome: 'Income',
    trendsSavings: 'Savings',
  },

  budget: {
    totalBudgetForPrefix: 'Total budget for',
    totalBudgetLabel: 'Total budget',
    spent: 'Spent',
    budgeted: 'Budgeted',
    leftToBudget: 'Left to budget',
    whatYoullSpendOn: "This month's budgeted categories",
    sectionTitle: 'Budget',
    editAction: 'Edit',
    deleteAction: 'Delete',
    deleteConfirmTitle: 'Delete this category?',
    deleteConfirmMessage: "This can't be undone.",
    spentOfSuffix: 'of',
    spentSuffix: 'spent',
    addCategory: 'Add category',
    footerNote: 'Categories and budgets carry over automatically when a new month starts.',
    chooseMonth: 'Choose month',
    addCategoryTitle: 'Add category',
    editCategoryTitleSuffix: 'budget',
    typeLabel: 'Type',
    typeLabels: {
      Expense: 'Expense',
      Income: 'Income',
      Savings: 'Savings',
      Transfer: 'Transfer',
    } as const,
    categoryLabel: 'Category',
    categoryPlaceholder: 'Choose a category',
    noCategoriesLeft: 'Every category of this type already has a budget this month.',
    showMorePrefix: 'Show more',
    showLess: 'Show less',
    monthTransactionsTitle: 'Transactions this month',
    recordTransaction: 'Add New',
    noMonthTransactionsPrefix: 'No transactions recorded for',
    noMonthTransactionsSuffix: 'yet.',
    viewAllMonthTransactionsPrefix: 'View all',
    viewAllMonthTransactionsSuffix: 'transactions this month',
    descriptionLabel: 'Description',
    descriptionPlaceholder: 'What is this category for?',
    amountLabel: 'Amount',
    repeatsLabel: 'Repeats',
    monthsSuffix: 'months',
    recurrenceOptions: [
      { key: 'monthly', label: 'Every month' },
      { key: 'limited', label: 'For a few months' },
      { key: 'once', label: 'Just this month' },
    ] as const,
    recurrenceMonthly: 'Repeats every month',
    recurrenceLimitedPrefix: 'Repeats for',
    recurrenceLimitedSuffixOne: 'more month',
    recurrenceLimitedSuffixMany: 'more months',
    recurrenceOnce: 'This month only',
    projectedIncomeLabel: 'Projected income',
    overspendWarningPrefix: "You're planning to overspend by",
    editRecurrenceLabel: 'Repeats',
    deleteRecurringHint: 'Only removes it from this month — every other month keeps it.',
    editPlan: 'Edit budget plan',
    configTitle: 'Budget plan',
    savingsModeLabel: 'Planned savings as',
    savingsModeFixed: 'Fixed amount',
    savingsModePercent: '% of income',
    savingsAmountLabel: 'Savings amount',
    savingsPercentLabel: 'Savings percent',
    projectedColumnLabel: 'Projected',
    actualColumnLabel: 'Actual',
    incomeRowLabel: 'Income',
    savingsRowLabel: 'Savings',
  },

  transactionHistory: {
    title: 'Transactions',
    timeRangeWeek: 'Week',
    timeRangeMonth: 'Month',
    timeRangeQuarter: 'Quarter',
    timeRangeYear: 'Year',
    timeRangeAll: 'All time',
    trendTitle: 'Budget vs. spend',
    trendBudgetedLabel: 'Budgeted',
    trendSpentLabel: 'Spent',
    timeRangeFilterLabel: 'Filter by time range',
    recordsTitle: 'Records',
    noTransactions: 'No transactions in this range.',
    searchPlaceholder: 'Search description, category, account…',
    filterTypeLabel: 'Type',
    filterTypeAll: 'All types',
    filterAccountLabel: 'Account',
    filterAccountAll: 'All accounts',
    clearFilters: 'Clear filters',
    noMatches: 'No transactions match your search or filters.',
    backfilledTag: 'Backfilled',
    reconciliationTag: 'Reconciliation',
  },

  editTransaction: {
    title: 'Edit transaction',
    back: 'Back',
    notFound: "This transaction couldn't be found.",
    descriptionLabel: 'Description',
    typeLabel: 'Type',
    categoryLabel: 'Category',
    categoryPlaceholder: 'Choose a category',
    amountLabel: 'Amount',
    accountLabel: 'Account',
    dateLabel: 'Date',
    saving: 'Saving…',
    dangerZoneTitle: 'Delete',
    deleteHint: "Reverses this transaction's effect on its wallet's balance and removes it for good. This can't be undone.",
    deleteButton: 'Delete transaction',
    deleteConfirmPrompt: 'Delete this transaction? Its wallet balance will be adjusted back to what it was before this entry.',
    deleteConfirm: 'Delete permanently',
    deleteCancel: 'Cancel',
    deleting: 'Deleting…',
  },

  paymentsCalendar: {
    title: 'Payments Calendar',
    upcoming: 'Upcoming',
    viewAll: 'View all',
    filterByDueDate: 'Filter by due date',
    noUpcomingPayments: "You're all caught up — nothing due soon.",
    markAsPaid: 'Mark as paid',
    recurring: 'Recurring',
    oneTime: 'One-time',
    recentlyCaptured: 'Recently Captured',
    capturedSuffix: 'added to transactions',
    confirmTransactionTitle: 'Confirm Transaction',
    confirmHint: 'Review the details below — confirming adds this to your transactions and removes it from the calendar.',
    reviewDescription: 'Description',
    reviewCategory: 'Category',
    reviewAccount: 'Account',
    reviewAmount: 'Amount',
    reviewDate: 'Date',
    addPayment: 'Add planned payment',
    addPaymentTitle: 'Add planned payment',
    addPaymentHint: 'A real bill with a due date — Netflix, rent, an insurance premium. Several can count against the same budget category.',
    categoryLabel: 'Category',
    categoryPlaceholder: 'Choose a category',
    noExpenseCategories: 'Add an expense category on the Budget screen first.',
    descriptionLabel: 'Description',
    descriptionPlaceholder: 'e.g. Netflix',
    amountLabel: 'Amount',
    dueDateLabel: 'Due date',
    chooseDate: 'Choose a date',
    accountLabel: 'Account',
    accountOptional: 'No specific account',
    repeatsLabel: 'Repeats',
    everyPrefix: 'Every',
    endAfterLabel: 'End after (occurrences)',
    endAfterPlaceholder: 'Leave blank to repeat forever',
    monthsSuffix: 'months',
    deletePaymentLabel: 'Delete planned payment',
    deletePaymentConfirmTitle: 'Delete this planned payment?',
    deletePaymentConfirmMessage: "This removes it from your upcoming payments. It won't affect any transaction already recorded from it.",
  },

  onboarding: {
    walletsTitle: 'Add your wallets',
    walletsSubtitle: 'Add at least one account to track — a cash wallet, bank account, or savings account.',
    categoriesTitle: 'Set up your categories',
    categoriesSubtitle: 'Add at least one category — tap a suggestion or create your own.',
    budgetTitle: 'Plan your first budgets',
    budgetSubtitle: 'Optional — set a monthly amount for any category, or skip this for now.',
    namePlaceholder: 'Name',
    startingBalancePlaceholder: 'Starting balance',
    addWallet: 'Add wallet',
    addCategory: 'Add category',
    addBudgetItem: 'Add budget item',
    amountPlaceholder: 'Monthly amount',
    categoryPlaceholder: 'Choose a category',
    suggestions: 'Suggestions',
    back: 'Back',
    continueLabel: 'Continue',
    finishSetup: 'Finish setup',
    budgetItemsAddedSuffix: 'budget items added',
    skipOnboarding: 'Skip for now',
  },

  wallets: {
    title: 'Wallets',
    totalAcrossWalletsSuffix: 'XAF across all wallets',
    addWallet: 'Add wallet',
    addWalletTitle: 'Add a wallet',
    nameLabel: 'Name',
    namePlaceholder: 'e.g. Everyday spending',
    shortNameLabel: 'Short name (for charts)',
    shortNamePlaceholder: 'e.g. CASH',
    shortNameHint: 'Up to 5 characters — shown on the Home screen wallet chart.',
    typeLabel: 'Type',
    currencyLabel: 'Currency',
    startingBalanceLabel: 'Starting balance',
    archivedTitle: 'Archived',
  },

  walletDetail: {
    periods: ['Week', 'Month', 'Quarter'] as const,
    editWallet: 'Edit wallet',
    editWalletTitle: 'Edit wallet',
    nameLabel: 'Name',
    startingBalanceLabel: 'Starting balance (seed amount)',
    startingBalanceHint: "Editing this shifts the current balance by the same amount — every transaction since stays intact.",
    cashflowTitle: 'Cashflow',
    cashflowLegendIn: 'In',
    cashflowLegendOut: 'Out',
    spendingTrendTitle: 'Spending trend',
    transferDestinationsTitle: 'Where money leaves to',
    emptyTransferDestinations: 'No transfers out of this wallet yet.',
    upcomingPaymentsTitle: 'Needed for upcoming payments',
    upcomingPaymentsNone: 'No planned payments due from this wallet in the next 30 days.',
    upcomingPaymentsCovered: 'Covered by the available balance.',
    upcomingPaymentsShortPrefix: 'Short by',
    notSpendableLabel: 'Not spendable',
    notSpendableHint: "Excludes this wallet's balance from Home's Spendable total, without blocking transactions.",
    frozenLabel: 'Frozen',
    frozenHint: 'Blocks every transaction and transfer on this wallet until unfrozen.',
    frozenBadge: 'Frozen',
    notSpendableBadge: 'Not spendable',
    lockedAmountLabel: 'Locked amount',
    lockedAmountHint:
      "Sets aside part of this wallet's balance — e.g. money pushed here as savings — blocked from being spent without freezing the rest of the wallet.",
    lockedBadgeSuffix: 'locked',
    availablePrefix: 'Available to spend:',
    dangerZoneTitle: 'Archive',
    archiveWallet: 'Archive wallet',
    archiveWalletHint: 'Hides it from your wallets list and every picker. Its history stays intact.',
    archivedBadge: 'Archived',
    unarchiveWallet: 'Unarchive wallet',
    unarchiveWalletHint: 'Brings it back into your wallets list and every picker.',
    archiveFundsPrompt: 'What should happen to the remaining balance?',
    archiveModeTransfer: 'Move it to another wallet',
    archiveModeDiscard: 'Write it off — this wallet is closing for good',
    archiveDestinationLabel: 'Move balance to',
    archiveConfirm: 'Archive wallet',
    archiving: 'Archiving…',
    archiveCancel: 'Cancel',
  },

  addTransaction: {
    title: 'Add transaction',
    chooseTransactionPrefix: 'Choose transaction',
    provideTransactionPrefix: 'Provide transaction',
    stepType: 'type',
    stepCategory: 'category',
    stepDetails: 'details',
    stepReview: 'data',
    types: {
      expense: {
        label: 'Expense',
        description: 'Record a recent expense transaction.',
      },
      income: {
        label: 'Income',
        description: 'Let us know if new money came in.',
      },
      transfer: {
        label: 'Transfer',
        description: 'Move money from one wallet to another.',
      },
      savings: {
        label: 'Savings',
        description: 'Register a new savings activity.',
      },
    },
    descriptionLabel: 'Description',
    descriptionPlaceholder: 'e.g Yango payment for trip to santa Lucia',
    noBudgetTitle: 'No budget set for this month yet.',
    noBudgetBody: "You haven't budgeted any category for this month. Add a budget, or record this as unplanned.",
    addBudgetCta: 'Add a budget',
    recordUnplannedCta: 'Record as unplanned',
    showBudgetedOnlyCta: 'Show budgeted categories only',
    unplannedNotice: "Showing every category — this one isn't in this month's budget.",
    transactionDate: 'Transaction Date',
    fromAccount: 'From',
    toAccount: 'To',
    chargesLabel: 'Charges',
    chargesHint: 'Fees deducted from the source wallet, on top of the amount.',
    incomeAccount: 'Income Account',
    expenseAccount: 'Expense Account',
    reviewTitle: 'Transaction Data',
    reviewDescription: 'Description',
    reviewCategory: 'Category',
    reviewAmount: 'Amount',
    reviewCharges: 'Charges',
    reviewType: 'Type',
    reviewAccounts: 'Accounts',
    reviewDate: 'Date',
    addingAnPrefix: 'Adding an',
    chooseDate: 'Choose date',
    chooseAccount: 'Choose account',
    saving: 'Saving…',
    explainUnjustifiedLabel: 'This explains part of my unaccounted balance',
    explainUnjustifiedHint: 'Unaccounted available:',
  },

  settings: {
    title: 'Settings',
    shareTitle: 'Share Dreda',
    shareMeta: 'Invite friends to try the app',
    shareCopied: 'Link copied!',
    shareText: 'Track your spending effortlessly with Dreda.',
    currency: 'Currency',
    appPin: 'App PIN',
    appPinMeta: 'Change your unlock PIN',
    dailyReminders: 'Daily reminders',
    dailyRemindersCaption: "You'll be reminded to log your spending at these times each day.",
    addReminder: 'Add reminder',
    signOut: 'Sign out',
    chooseCurrency: 'Choose currency',
    searchCurrenciesPlaceholder: 'Search currencies',
    confirmPinTitle: 'Confirm current PIN',
    currentPinLabel: 'Current 5-digit PIN',
    changePinTitle: 'Change app PIN',
    newPinLabel: 'New 5-digit PIN',
    requirePin: 'Require PIN',
    requirePinMeta: 'Off skips the PIN screen — the app opens straight to Home.',
    createCategory: 'Categories',
    createCategoryMeta: 'View, or add a new Expense, Income, or Savings category',
    dataSectionTitle: 'Data',
    downloadTemplate: 'Download CSV template',
    downloadTemplateMeta: 'Fill it in with your historical transactions',
    exportTransactions: 'Export transactions',
    exportTransactionsMeta: 'Download everything as a CSV file',
    importTransactions: 'Import transactions',
    importTransactionsMeta: 'Upload a filled-in CSV to add historical data',
    auditSectionTitle: 'Audit',
    reconcileBalances: 'Audit & reconcile balances',
    reconcileBalancesMeta: 'Check every wallet against its own transaction history',
  },

  reconcile: {
    title: 'Audit & reconcile balances',
    introTitle: 'What this checks',
    introBody:
      "Recomputes every wallet's balance from its starting balance plus every transaction AND transfer that's ever touched it, and compares that against the balance the app currently shows. They should always match — a mismatch usually means an entry landed outside the normal flow (a CSV import, historical data seeded out of order, a direct edit). Nothing changes until you review the results and choose to apply a fix.",
    runButton: 'Run audit',
    runningLabel: 'Checking every wallet…',
    summaryChecked: 'Wallets checked',
    summaryEntries: 'Transactions & transfers checked',
    summaryMismatches: 'Mismatches found',
    summaryMatched: 'Already correct',
    checkedAtPrefix: 'Last checked',
    perRowTransactionsLabel: 'transactions',
    perRowTransfersLabel: 'transfers',
    orphanedTitle: 'Entries pointing at a wallet that no longer resolves',
    orphanedBody:
      "These transactions or transfers reference an account id that doesn't match any wallet you currently have — a sign of a bad migration or import. They're excluded from every wallet's balance above (there's nowhere to attribute them), so fixing them by hand (in Firestore directly, or by re-pointing them to the right wallet) and re-running the audit is the only way to bring them back into the numbers.",
    orphanedTransferFrom: 'missing source wallet',
    orphanedTransferTo: 'missing destination wallet',
    orphanedTransactionAccount: 'missing wallet',
    negativeWarningTitle: 'Some wallets would go negative',
    negativeWarningBody:
      "Reconciling these wallets would leave them below zero — that usually means there are expenses on record that weren't actually covered by money that came in. Review them before applying.",
    cleanTitle: 'All balances match',
    cleanBody: "Every wallet's balance already matches its transaction history — nothing to fix.",
    mismatchListTitle: 'Mismatches found',
    storedLabel: 'Currently shows',
    expectedLabel: 'Should be',
    differenceLabel: 'Difference',
    negativeBadge: 'Goes negative',
    applyButton: 'Apply selected corrections',
    applyingLabel: 'Applying…',
    appliedNotice: 'Corrections applied — balances updated.',
    rerunButton: 'Run audit again',
    noneSelected: 'Select at least one wallet to apply a correction to.',
  },

  reconciliation: {
    title: 'Reconciliation',
    entryLabel: 'Reconciliation',
    entryMeta: 'Report what your accounts actually hold and close the gap over time',
    unaccountedLabel: 'Unaccounted balance',
    gapPositiveExplainer:
      "Your ledger says you should have more money than you've reported having. Log a missed expense below to explain part of it, or start a fresh check.",
    gapNegativeExplainer:
      "Your ledger says you should have less money than you've reported having. Log a missed income below to explain part of it, or start a fresh check.",
    gapZeroExplainer: 'Your ledger matches what you last reported — nothing unaccounted for.',
    savedNotice: 'Reconciliation saved.',
    reconcileNowButton: 'Reconcile now',
    reconcileNowTitle: 'Reconcile now',
    reconcileNowHint: 'Enter what each account actually holds right now.',
    ledgerPrefix: 'Ledger:',
    totalLedgerLabel: 'Total ledger',
    totalReportedLabel: 'Total reported',
    gapLabel: 'Gap',
    saveReconciliation: 'Save reconciliation',
    saving: 'Saving…',
    explainedTitle: 'Explained so far',
    noExplained: 'Nothing explained yet.',
    viewHistory: 'View reconciliation history',
    historyTitle: 'Reconciliation history',
    noHistory: 'No reconciliation checks yet.',
    gapAtCheckPrefix: 'Gap:',
    breakdownTitle: 'Per-account breakdown',
    columnAccount: 'Account',
    columnLedger: 'Ledger',
    columnReported: 'Reported',
    columnDifference: 'Difference',
  },

  backfill: {
    title: 'Backfill a recurring transaction',
    entryLabel: 'Backfill transactions',
    entryMeta: 'Spread a recurring transaction across months that predate real usage',
    whatLabel: 'What is it?',
    whatPlaceholder: 'Salary',
    typeLabel: 'Type',
    amountLabel: 'Amount per occurrence',
    categoryLabel: 'Category',
    categoryPlaceholder: 'Choose a category',
    accountLabel: 'Account',
    fromMonthLabel: 'From month',
    toMonthLabel: 'To month',
    dayOfMonthLabel: 'Day of month',
    explainToggleLabel: 'This explains part of my unaccounted balance',
    explainToggleHint: 'Unaccounted available:',
    previewButton: 'Preview',
    previewTitle: 'Preview',
    previewCountSuffix: 'transactions will be created',
    previewTotalPrefix: 'Total:',
    confirmButton: 'Confirm',
    backToEdit: 'Back to edit',
    committing: 'Creating…',
    rangeTooLong: 'A backfill spread covers at most 36 months — narrow the range and try again.',
    manageBatchesLink: 'Manage backfill batches',
    batchesTitle: 'Backfilled transactions',
    noBatches: 'No backfilled batches yet.',
    batchCountSuffix: 'transactions',
    viewBatch: 'View',
    deleteBatch: 'Delete batch',
    deleteBatchConfirmTitle: 'Delete this backfill batch?',
    deleteBatchConfirmMessage:
      'This permanently removes every transaction in this batch and reverses their effect on the wallet balance. This cannot be undone.',
  },

  auditReports: {
    title: 'Financial audit reports',
    entryLabel: 'Financial audit reports',
    entryMeta: 'Generate a Month/Quarter/Year report on net worth, cash flow, and budget health',
    periodLabel: 'Period',
    periodMonth: 'Month',
    periodQuarter: 'Quarter',
    periodYear: 'Year',
    yearLabel: 'Year',
    monthLabel: 'Month',
    quarterLabel: 'Quarter',
    generateButton: 'Generate report',
    generatingLabel: 'Generating…',
    pastReportsTitle: 'Past reports',
    noReports: 'No reports generated yet — pick a period above and generate your first one.',
    generatedAtPrefix: 'Generated',
    deleteReport: 'Delete report',
    deleteReportConfirmTitle: 'Delete this report?',
    deleteReportConfirmMessage: "This deletes the saved snapshot for good. You can always generate a new one for the same period, but it won't necessarily match this one if the underlying data has changed since.",
  },

  auditReportDetail: {
    exportPdf: 'Export as PDF',
    printedFooter: 'Generated by Dreda',
    sectionExecutiveSummary: 'Executive Summary',
    sectionBalanceSheet: 'Balance Sheet',
    sectionCashFlow: 'Cash Flow Analysis',
    sectionSpendingHabits: 'Spending Habits',
    sectionBudgetAdherence: 'Budget Adherence',
    sectionFinancialHealth: 'Financial Health Metrics',
    sectionGoalsDebt: 'Goals & Debt Summary',
    sectionAppendix: 'Appendix',
    redFlagsTitle: 'Red flags',
    noRedFlags: 'No red flags this period.',
    goalsStatusLabel: 'Goals',
    debtStatusLabel: 'Debt',
    netWorthSparklineTitle: 'Estimated net worth trend (12 months)',
    assetsTitle: 'Assets',
    liabilitiesTitle: 'Liabilities',
    netWorthLabel: 'Net worth',
    compositionTitle: 'Account composition',
    periodSummaryTitle: 'Period summary',
    incomeLabel: 'Income',
    expenseLabel: 'Expense',
    netLabel: 'Net',
    savingsRateLabel: 'Savings rate',
    trendTitle: '12-month trend',
    incomeBreakdownTitle: 'Income breakdown',
    expenseBreakdownTitle: 'Expense breakdown',
    wastefulAlertsTitle: 'Wasteful spending alerts',
    categoryTrendsTitle: 'Category trends (12 months)',
    volatilityTitle: 'Volatility analysis',
    topCategoriesTitle: 'Top categories',
    recurringVsVariableTitle: 'Recurring vs. variable spend',
    recurringLabel: 'Recurring',
    variableLabel: 'Variable',
    notesTitle: 'Observations',
    budgetTableTitle: 'Budget vs. actual',
    consistencyScoreLabel: 'Consistency score',
    chronicOveragesTitle: 'Chronic overages',
    noChronicOverages: 'No chronic overages this period.',
    columnCategory: 'Category',
    columnBudget: 'Budget',
    columnActual: 'Actual',
    columnVariance: 'Var %',
    columnAnnualImpact: 'Annual impact',
    columnStatus: 'Status',
    healthOverallTitle: 'Overall assessment',
    incomeLossTitle: 'Income-loss contingency',
    rankedByUrgencyTitle: 'Ranked by urgency',
    goalsTableTitle: 'Goals progress',
    debtsTableTitle: 'Debts',
    payoffOpportunityTitle: 'Payoff opportunity',
    columnGoal: 'Goal',
    columnTarget: 'Target',
    columnSaved: 'Saved',
    columnProgress: 'Progress',
    columnDeadline: 'Deadline',
    columnDebt: 'Debt',
    columnBalance: 'Balance',
    columnMonthsToPayoff: 'Months to payoff',
    columnPriority: 'Priority',
    transactionLogTitle: 'Transaction log',
    totalsByCategoryTitle: 'Totals by category',
    columnDate: 'Date',
    columnDescription: 'Description',
    columnAccount: 'Account',
    columnType: 'Type',
    columnAmount: 'Amount',
    truncatedNoticePrefix: 'Showing first',
    truncatedNoticeSuffix: 'transactions — more exist in this period.',
    notFound: "This report couldn't be found.",
  },

  importCsv: {
    title: 'Import transactions',
    chooseFile: 'Choose a CSV file',
    changeFile: 'Choose a different file',
    hint: 'Use the template from Settings — Date, Type, Account, Category, Amount, Description. Account and Category must match names you already have.',
    readyLabel: 'Ready to import',
    issuesLabel: 'Rows with issues',
    importButton: 'Import',
    importingLabel: 'Importing…',
    doneTitle: 'Import complete',
    importedLabel: 'Imported',
    failedLabel: 'Failed',
    doneButton: 'Back to Settings',
    noRowsError: 'No valid rows to import — fix the issues below and choose the file again.',
  },

  addBudgetCategory: {
    title: 'Add budget category',
    back: 'Back',
    typeLabel: 'Type',
    categoryLabel: 'Category',
    categoryPlaceholder: 'Choose a category',
    noCategoriesLeft: 'Every category of this type already has a budget this month.',
    cantFindCategory: "Can't find your category?",
    createNewCategory: 'Create a new category',
    cancelCreateCategory: 'Cancel',
    descriptionLabel: 'Description',
    descriptionPlaceholder: 'What is this category for?',
    amountLabel: 'Amount',
    repeatsLabel: 'Repeats',
    save: 'Add category',
    saving: 'Adding…',
  },

  createCategory: {
    title: 'Create category',
    nameLabel: 'Name',
    namePlaceholder: 'e.g. Groceries',
    typeLabel: 'Type',
    descriptionLabel: 'Description',
    descriptionPlaceholder: 'What is this category for? (optional)',
    save: 'Create category',
    saving: 'Creating…',
  },

  categories: {
    title: 'Categories',
    empty: "You haven't created any categories yet.",
    createCta: 'Create category',
    editTitle: 'Edit category',
    saveChanges: 'Save changes',
    savingChanges: 'Saving…',
  },

  goals: {
    tabGoals: 'Goals',
    tabDebt: 'Debt',
    emptyGoals: "No savings goals yet — add one to start tracking progress toward it.",
    emptyDebt: 'No debts tracked yet.',
    addGoal: 'Add goal',
    allItemsLink: 'See everything left to do, ranked →',
    addDebt: 'Add debt',
    completedOfSuffix: 'of',
    itemsDone: 'items done',
    deadlinePrefix: 'By',
    archiveAction: 'Archive',
    totalDebtLabel: 'Total debt',
    byPriorityLabel: 'By priority',
    priorityHigh: 'High',
    priorityMedium: 'Medium',
    priorityLow: 'Low',
    nextPaymentPrefix: 'Next payment:',
    totalDebtTrendTitle: 'Total debt over time',
    archiveGoalConfirmTitle: 'Archive this goal?',
    archiveGoalConfirmMessage: "It'll be hidden from your goals list. This can't be undone from the app.",
    archiveDebtConfirmTitle: 'Archive this debt?',
    archiveDebtConfirmMessage: "It'll be hidden from your debt list. This can't be undone from the app.",
  },

  goalDetail: {
    headerTitle: 'Goal',
    backLabel: 'Back',
    progressLabel: 'Progress',
    deadlinePrefix: 'Target date:',
    lineItemsTitle: 'Line items',
    addLineItem: 'Add item',
    emptyLineItems: 'No line items yet — break this goal into smaller costs to track.',
    markComplete: 'Mark complete',
    completedTag: 'Done',
    frozenAvailable: 'Frozen funds available',
    frozenInsufficient: 'Not enough frozen funds — freeze more in Wallets first',
    deleteLineItem: 'Delete',
    deleteLineItemConfirmTitle: 'Delete this line item?',
    deleteLineItemConfirmMessage: "This can't be undone.",
    archiveGoal: 'Archive goal',
    save: 'Save',
    saving: 'Saving…',
    nameLabel: 'Name',
    amountLabel: 'Amount',
    descriptionLabel: 'Description (optional)',
    editGoal: 'Edit goal',
    editLineItem: 'Edit',
    editLineItemTitle: 'Edit item',
  },

  createGoal: {
    title: 'New goal',
    nameLabel: 'Name',
    namePlaceholder: 'e.g. Emergency fund',
    descriptionLabel: 'Description (optional)',
    deadlineLabel: 'Target date (optional)',
    currencyLabel: 'Currency',
    save: 'Create goal',
    saving: 'Creating…',
    addLineItemsHint: 'Add line items after creating the goal.',
  },

  markLineItemComplete: {
    title: 'Mark as paid',
    accountLabel: 'Pay from wallet',
    categoryLabel: 'Category',
    dateLabel: 'Date',
    descriptionLabel: 'Description (optional)',
    save: 'Confirm payment',
    saving: 'Saving…',
    frozenBlocked: 'Not enough frozen funds in this wallet for this item.',
  },

  debtDetail: {
    headerTitle: 'Debt',
    backLabel: 'Back',
    balanceLabel: 'Current balance',
    principalLabel: 'Original amount',
    repaidLabel: 'Repaid',
    priorityLabel: 'Priority',
    typeLabel: 'Type',
    typeCash: 'Cash debt',
    typeExisting: 'Existing debt',
    paymentPlanLabel: 'Payment plan',
    noPaymentPlan: 'No recurring plan',
    nextPaymentPrefix: 'Next payment:',
    recordRepayment: 'Record repayment',
    repaymentHistory: 'Repayment history',
    emptyRepayments: 'No repayments recorded yet.',
    archiveDebt: 'Archive debt',
    notesLabel: 'Notes',
    linkedToWallet: 'Linked to a wallet transaction',
    notLinked: 'Not linked to a wallet',
    editDebt: 'Edit debt',
    editPlan: 'Edit plan',
    saveChanges: 'Save changes',
    savingChanges: 'Saving…',
    trendTitle: 'Balance over time',
  },

  createDebt: {
    title: 'New debt',
    nameLabel: 'Name',
    namePlaceholder: 'e.g. Car loan',
    descriptionLabel: 'Description (optional)',
    typeLabel: 'Type',
    typeCash: 'Cash debt — borrowed money, affects a wallet balance',
    typeExisting: 'Existing debt — property/obligation, no wallet impact unless linked',
    walletLabel: 'Wallet',
    walletHint: 'The borrowed amount is credited to this wallet, and repayments default to debiting it back.',
    noWalletOption: 'No wallet yet',
    walletBackfillHint: 'The principal will be credited to this wallet when you save.',
    principalLabel: 'Principal amount',
    currencyLabel: 'Currency',
    priorityLabel: 'Priority',
    startDateLabel: 'Start date',
    notesLabel: 'Notes (optional)',
    recurringToggle: 'Set up a recurring payment plan',
    recurringAmountLabel: 'Amount per payment',
    recurringIntervalLabel: 'Interval',
    recurringNextDateLabel: 'Next payment date',
    save: 'Create debt',
    saving: 'Creating…',
  },

  recordRepayment: {
    title: 'Record repayment',
    amountLabel: 'Amount',
    dateLabel: 'Date',
    notesLabel: 'Notes (optional)',
    accountLabel: 'Pay from wallet',
    categoryLabel: 'Category',
    cashHint: 'This records as an expense transaction, debited from the selected wallet.',
    existingWithAccountHint: 'This records as an expense transaction from the selected wallet.',
    existingNoAccountHint: 'This records the repayment without touching a wallet balance.',
    linkWalletToggle: 'Link this repayment to a wallet transaction',
    save: 'Save repayment',
    saving: 'Saving…',
  },

  signIn: {
    title: 'Welcome back !',
    tagline: 'Sign in to keep capturing tasks and spending in two taps.',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    submit: 'Sign in',
    submitting: 'Signing in…',
    forgotPassword: 'Forgot password?',
    resetEmailSent: 'Password reset email sent — check your inbox.',
    or: 'or continue with',
    continueWithGoogle: 'Google',
    continueWithApple: 'Apple',
    footerPrompt: "Don't have an account?",
    footerLink: 'Create one',
  },

  marketing: {
    eyebrow: 'An everyday companion',
    headline: 'Your Money and Time all in one place.',
    lead:
      'Optimize how you track your tasks across projects and money across multiple wallets, all in one place.',
    body:
      " Dreda is a simple, fast, and intuitive app that helps you manage your time and finances effortlessly.",
    getStarted: 'Get started',
    howToInstall: 'How to install',
  },

  offline: {
    title: "You're offline",
    tagline: "No connection right now. Reconnect to keep tracking spending — your last-synced Home dashboard is still available.",
    retry: 'Try again',
  },

  signUp: {
    title: 'Welcome !',
    tagline: 'Join the league of people using Dreda\'s intuitive interface to manage their time and finances for free on the go.',
    nameLabel: 'Name',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    submit: 'Create account',
    submitting: 'Creating account…',
    or: 'or continue with',
    continueWithGoogle: 'Google',
    continueWithApple: 'Apple',
    footerPrompt: 'Already have an account?',
    footerLink: 'Sign in',
  },

  projects: {
    title: 'Projects',
    taskBasketTitle: 'TASK Basket',
    viewAllTasksLabel: 'View all tasks',
    tabAreas: 'Areas',
    tabProjects: 'Projects',
    tabArchive: 'Archive',
    overviewToday: 'Due today',
    overviewThisWeek: 'Due this week',
    overviewOverdue: 'Overdue',
    overviewAllTasks: 'Pending',
    emptyAreas: 'No areas yet — add one to start organizing your projects.',
    emptyProjects: 'No projects yet.',
    emptyArchive: 'Nothing archived yet.',
    newArea: 'New area',
    newProject: 'New project',
    addAreaTitle: 'Add an area',
    areaNameLabel: 'Name',
    areaNamePlaceholder: 'e.g. Home',
    colorLabel: 'Color',
    archiveAction: 'Archive',
    restoreAction: 'Restore',
    archivedAreasTitle: 'Areas',
    archivedProjectsTitle: 'Projects',
    projectCountSuffix: 'projects',
    taskCountSuffix: 'tasks',
    archiveAreaConfirmTitle: 'Archive this area?',
    archiveAreaConfirmMessage: "It'll be hidden from your areas list. You can restore it from Archive any time.",
    archiveProjectConfirmTitle: 'Archive this project?',
    archiveProjectConfirmMessage: "It'll be hidden from your projects list. You can restore it from Archive any time.",
  },

  createProject: {
    title: 'New project',
    nameLabel: 'Name',
    namePlaceholder: 'e.g. Repaint the fence',
    areaLabel: 'Area (optional)',
    noAreaOption: 'No area',
    colorLabel: 'Color',
    plannedEndDateLabel: 'End date (optional)',
    notesLabel: 'Description',
    save: 'Create project',
    saving: 'Creating…',
  },

  areaDetail: {
    headerTitle: 'Area',
    backLabel: 'Back',
    projectsTitle: 'Projects',
    tasksTitle: 'Tasks',
    emptyProjects: 'No projects in this area yet.',
    emptyTasks: 'No area-level tasks yet.',
    addTask: 'Add task',
    archiveArea: 'Archive area',
  },

  projectDetail: {
    headerTitle: 'Project',
    backLabel: 'Back',
    onTrack: 'On track',
    behindPlanSuffix: 'days behind plan',
    statTasks: 'Tasks',
    statCompleted: 'Completed',
    tasksTitle: 'Tasks',
    addTask: 'Add task',
    emptyTasks: 'No tasks yet.',
    archiveProject: 'Archive project',
    plannedEndPrefix: 'Planned:',
  },

  taskEdit: {
    addTitle: 'Add task',
    editTitle: 'Edit task',
    titleLabel: 'Title',
    titlePlaceholder: 'What needs doing?',
    statusLabel: 'Status',
    dueDateLabel: 'Due date (optional)',
    notesLabel: 'Notes (optional)',
    save: 'Save',
    saving: 'Saving…',
    deleteTask: 'Delete task',
    deleteConfirmTitle: 'Delete this task?',
    deleteConfirmMessage: "This can't be undone.",
  },
} as const;
