// Every static, user-facing string in the app lives here. Screens read them
// through useStrings() instead of hardcoding text inline — this is the one
// file to open to change copy anywhere in the product.

export const stringConstants = {
  common: {
    currency: 'XAF',
    change: 'Change',
    save: 'Save',
    continueLabel: 'Continue',
    confirm: 'Confirm',
    cancel: 'Cancel',
    back: 'Back',
    add: 'Add',
  },

  months: [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December',
  ],

  splash: {
    wordmark: 'dreda',
    headline: 'Track Your Spending and Time  Effortlessly',
    tagline:
      'Manage your time and finances easily using our intuitive user-friendly interface and set goals you can monitor.',
    getStarted: 'Get Started',
    inviteNotePrefix: 'This is an invite only platform, so if you do not have an account, get an invite at',
    inviteLink: 'www.dreda.com',
  },

  pin: {
    title: 'Enter Account PIN',
    titleCreate: 'Create Your PIN',
    continueLabel: 'Continue',
    footerNotePrefix: 'This is an invite only platform, if you have forgotten your pin, visit',
    footerNoteSuffix: 'to reset it.',
    footerLink: 'www.dreda.com',
  },

  home: {
    balanceLabel: 'Your Balance',
    spendableLabel: 'Spendable',
    quickActionAddNew: 'Add New',
    quickActionSeeBudget: 'See Budget',
    quickActionHistory: 'History',
    quickActionSync: 'Sync',
    wallets: 'Wallets',
    spendingBreakdown: 'Cashflow',
    periodWeek: 'Week',
    periodMonth: 'Month',
    periodQuarter: 'Quarter',
    legendIncome: 'Income',
    legendExpense: 'Expense',
    savingsTrend: 'Savings Trend',
    budgets: 'Budgets',
    upcomingPayments: 'Upcoming Payments',
    noUpcomingPayments: "You're all caught up — nothing due soon.",
    noWallets: 'Add a wallet to see it here.',
    noBudgets: 'No budgets set yet this month.',
  },

  statistics: {
    acrossAllAccounts: 'Across all accounts',
    spending: 'Spending',
    totalOutflow: 'Total outflow',
    income: 'Income',
    totalInflow: 'Total inflow',
    netSavings: 'Net Savings',
    savingsRate: 'Savings Rate',
    activeAccountsSuffix: 'active accounts this month',
    spendingInsights: 'Spending Insights',
    topCategories: 'Top Categories',
    noSpendingThisMonth: 'Nothing spent yet this month.',
    thisMonthVsLastMonth: 'This Month vs Last Month',
    noComparisonYet: 'Not enough history yet to compare.',
  },

  budget: {
    totalBudgetForPrefix: 'Total budget for',
    totalBudgetLabel: 'Total budget',
    spent: 'Spent',
    budgeted: 'Budgeted',
    leftToBudget: 'Left to budget',
    whatYoullSpendOn: "What you'll spend on",
    spentOfSuffix: 'of',
    spentSuffix: 'spent',
    addCategory: 'Add category',
    footerNote: 'Categories and budgets carry over automatically when a new month starts.',
    chooseMonth: 'Choose month',
    addCategoryTitle: 'Add category',
    editCategoryTitleSuffix: 'budget',
    categoryLabel: 'Category',
    categoryPlaceholder: 'Choose a category',
    noCategoriesLeft: 'Every expense category already has a budget this month.',
    descriptionLabel: 'Description',
    descriptionPlaceholder: 'What is this category for?',
    amountLabel: 'Amount',
    repeatsLabel: 'Repeats',
    monthsSuffix: 'months',
    recurrenceOptions: [
      { key: 'monthly', label: 'Every month' },
      { key: 'limited', label: 'For a few months' },
      { key: 'once', label: 'Just this month' },
    ] as const,
    recurrenceMonthly: 'Repeats every month',
    recurrenceLimitedPrefix: 'Repeats for',
    recurrenceLimitedSuffixOne: 'more month',
    recurrenceLimitedSuffixMany: 'more months',
    recurrenceOnce: 'This month only',
    projectedIncomeLabel: 'Projected income',
    overspendWarningPrefix: "You're planning to overspend by",
    editRecurrenceLabel: 'Repeats',
    deleteRecurringHint: 'Only removes it from this month — every other month keeps it.',
    editPlan: 'Edit budget plan',
    configTitle: 'Budget plan',
    savingsModeLabel: 'Planned savings as',
    savingsModeFixed: 'Fixed amount',
    savingsModePercent: '% of income',
    savingsAmountLabel: 'Savings amount',
    savingsPercentLabel: 'Savings percent',
    projectedColumnLabel: 'Projected',
    actualColumnLabel: 'Actual',
    incomeRowLabel: 'Income',
    savingsRowLabel: 'Savings',
  },

  transactionHistory: {
    title: 'Transactions',
  },

  paymentsCalendar: {
    title: 'Payments Calendar',
    upcoming: 'Upcoming',
    viewAll: 'View all',
    filterByDueDate: 'Filter by due date',
    noUpcomingPayments: "You're all caught up — nothing due soon.",
    markAsPaid: 'Mark as paid',
    recurring: 'Recurring',
    oneTime: 'One-time',
    recentlyCaptured: 'Recently Captured',
    capturedSuffix: 'added to transactions',
    confirmTransactionTitle: 'Confirm Transaction',
    confirmHint: 'Review the details below — confirming adds this to your transactions and removes it from the calendar.',
    reviewDescription: 'Description',
    reviewCategory: 'Category',
    reviewAccount: 'Account',
    reviewAmount: 'Amount',
    reviewDate: 'Date',
    addPayment: 'Add planned payment',
    addPaymentTitle: 'Add planned payment',
    addPaymentHint: 'A real bill with a due date — Netflix, rent, an insurance premium. Several can count against the same budget category.',
    categoryLabel: 'Category',
    categoryPlaceholder: 'Choose a category',
    noExpenseCategories: 'Add an expense category on the Budget screen first.',
    descriptionLabel: 'Description',
    descriptionPlaceholder: 'e.g. Netflix',
    amountLabel: 'Amount',
    dueDateLabel: 'Due date',
    chooseDate: 'Choose a date',
    accountLabel: 'Account',
    accountOptional: 'No specific account',
    repeatsLabel: 'Repeats',
    everyPrefix: 'Every',
    endAfterLabel: 'End after (occurrences)',
    endAfterPlaceholder: 'Leave blank to repeat forever',
    monthsSuffix: 'months',
    deletePaymentLabel: 'Delete planned payment',
  },

  onboarding: {
    walletsTitle: 'Add your wallets',
    walletsSubtitle: 'Add at least one account to track — a cash wallet, bank account, or savings account.',
    categoriesTitle: 'Set up your categories',
    categoriesSubtitle: 'Add at least one category — tap a suggestion or create your own.',
    budgetTitle: 'Plan your first budgets',
    budgetSubtitle: 'Optional — set a monthly amount for any category, or skip this for now.',
    namePlaceholder: 'Name',
    startingBalancePlaceholder: 'Starting balance',
    addWallet: 'Add wallet',
    addCategory: 'Add category',
    addBudgetItem: 'Add budget item',
    amountPlaceholder: 'Monthly amount',
    categoryPlaceholder: 'Choose a category',
    suggestions: 'Suggestions',
    back: 'Back',
    continueLabel: 'Continue',
    finishSetup: 'Finish setup',
    budgetItemsAddedSuffix: 'budget items added',
  },

  wallets: {
    title: 'Wallets',
    totalAcrossWalletsSuffix: 'XAF across all wallets',
    addWallet: 'Add wallet',
    addWalletTitle: 'Add a wallet',
    nameLabel: 'Name',
    namePlaceholder: 'e.g. Everyday spending',
    typeLabel: 'Type',
    currencyLabel: 'Currency',
    startingBalanceLabel: 'Starting balance',
  },

  walletDetail: {
    periods: ['Week', 'Month', 'Quarter'] as const,
    editWallet: 'Edit wallet',
    editWalletTitle: 'Edit wallet',
    notSpendableLabel: 'Not spendable',
    notSpendableHint: "Excludes this wallet's balance from Home's Spendable total, without blocking transactions.",
    frozenLabel: 'Frozen',
    frozenHint: 'Blocks every transaction and transfer on this wallet until unfrozen.',
    frozenBadge: 'Frozen',
    notSpendableBadge: 'Not spendable',
  },

  addTransaction: {
    title: 'Add transaction',
    chooseTransactionPrefix: 'Choose transaction',
    provideTransactionPrefix: 'Provide transaction',
    stepType: 'type',
    stepCategory: 'category',
    stepDetails: 'details',
    stepReview: 'data',
    types: {
      expense: {
        label: 'Expense',
        description: 'Record a recent expense transaction.',
      },
      income: {
        label: 'Income',
        description: 'Let us know if new money came in.',
      },
      transfer: {
        label: 'Transfer',
        description: 'Move money from one wallet to another.',
      },
      savings: {
        label: 'Savings',
        description: 'Register a new savings activity.',
      },
    },
    descriptionLabel: 'Description',
    descriptionPlaceholder: 'e.g Yango payment for trip to santa Lucia',
    transactionDate: 'Transaction Date',
    fromAccount: 'From Account',
    toAccount: 'To Account',
    incomeAccount: 'Income Account',
    expenseAccount: 'Expense Account',
    reviewTitle: 'Transaction Data',
    reviewDescription: 'Description',
    reviewCategory: 'Category',
    reviewAmount: 'Amount',
    reviewType: 'Type',
    reviewAccounts: 'Accounts',
    reviewDate: 'Date',
    addingAnPrefix: 'Adding an',
    chooseDate: 'Choose date',
    chooseAccount: 'Choose account',
    saving: 'Saving…',
  },

  settings: {
    title: 'Settings',
    shareTitle: 'Share Dreda',
    shareMeta: 'Invite friends to try the app',
    shareCopied: 'Link copied!',
    shareText: 'Track your spending effortlessly with Dreda.',
    currency: 'Currency',
    appPin: 'App PIN',
    appPinMeta: 'Change your unlock PIN',
    dailyReminders: 'Daily reminders',
    dailyRemindersCaption: "You'll be reminded to log your spending at these times each day.",
    addReminder: 'Add reminder',
    signOut: 'Sign out',
    chooseCurrency: 'Choose currency',
    searchCurrenciesPlaceholder: 'Search currencies',
    changePinTitle: 'Change app PIN',
    newPinLabel: 'New 5-digit PIN',
  },

  signIn: {
    title: 'Welcome back !',
    tagline: 'Sign in to keep capturing tasks and spending in two taps.',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    submit: 'Sign in',
    submitting: 'Signing in…',
    forgotPassword: 'Forgot password?',
    resetEmailSent: 'Password reset email sent — check your inbox.',
    or: 'or continue with',
    continueWithGoogle: 'Google',
    continueWithApple: 'Apple',
    footerPrompt: "Don't have an account?",
    footerLink: 'Create one',
  },

  marketing: {
    eyebrow: 'An everyday companion',
    headline: 'Your Money and Time all in one place.',
    lead:
      'Optimize how you track your tasks across projects and money across multiple wallets, all in one place.',
    body:
      " Dreda is a simple, fast, and intuitive app that helps you manage your time and finances effortlessly.",
    getStarted: 'Get started',
    howToInstall: 'How to install',
  },

  offline: {
    title: "You're offline",
    tagline: "No connection right now. Reconnect to keep tracking spending — your last-synced Home dashboard is still available.",
    retry: 'Try again',
  },

  signUp: {
    title: 'Welcome !',
    tagline: 'Join the league of people using Dreda\'s intuitive interface to manage their time and finances for free on the go.',
    nameLabel: 'Name',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    submit: 'Create account',
    submitting: 'Creating account…',
    or: 'or continue with',
    continueWithGoogle: 'Google',
    continueWithApple: 'Apple',
    footerPrompt: 'Already have an account?',
    footerLink: 'Sign in',
  },
} as const;
